services:
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: atulya
      POSTGRES_PASSWORD: beriberigud
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

# our own image
  springpractice:
    container_name: springpractice_container
    image: 4ager/springpractice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer # To override spring.datasource.url (db is the db service from above
    ports:
      - "8080:8000" # exposed:internal
    networks:
      - db # use db network
    depends_on:
      - db # start db service before this
    restart: unless-stopped

    ## We can mention extra commands (instead we specify this in environment)
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer


networks:
  db:
    driver: bridge

volumes:
  db:
