services:
  db:
    container_name: postgres_container
    image: postgres:15.3
    environment:
      POSTGRES_USER: atulya
      POSTGRES_PASSWORD: beriberigud
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

# our own image for backend
  springpractice:
    container_name: springpractice_container
    image: 4ager/springpractice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer # To override spring.datasource.url (db is the db service from above
    ports:
      - "8080:8000" # exposed:internal
    networks:
      - db # use db network
    depends_on:
      - db # start db service before this
    restart: unless-stopped

    ## We can mention extra commands (instead we specify this in environment)
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer

  ## FRONTEND
  react-frontend:
    container_name: react-frontend
    image: 4ager/react-frontend
    build:
      context: frontend/react-frontend
      dockerfile: Dockerfile
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - springpractice
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db:
